DATABASE_NAME: 'mock_server'
DATABASE_HOST: 'localhost'
DATABASE_PORT: 5432
DATABASE_USER: 'postgres'
DATABASE_MAX_POOL_SIZE: 2
DATABASE_READ_TIME_OUT_MS: 100
DATABASE_WRITE_TIME_OUT_MS: 500
DATABASE_PASSWORD: ''